{% set name = "msmpi" %}
{% set version = "10.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nicogodet/Microsoft-MPI/archive/refs/tags/{{ version }}.tar.gz
  sha256: 4f7ad4ec7b043d26c38d201ea383bdafb3f8e68fe04c0d00a2dcacdafad6a204

build:
  number: 8
  skip: true  # [not win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - m2w64-toolchain        # [win]
    - m2-perl                # [win]
  run:
    - mpi 1.0 msmpi

test:
  files:
    - tests/*  # [win]
  requires:
    - {{ compiler('c') }}
    # These deps are needed for the mpi4py tests
    # - python
    # - pip
    # - cython
    # - setuptools
    # - git
  commands:
    # simple package integraty check
    - if not exist %LIBRARY_PREFIX%\\mingw-w64\\bin\\mpiexec.exe exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\\mingw-w64\\bin\\mingw-w64\\smpd.exe exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\\mingw-w64\\bin\\mingw-w64\\msmpi.dll exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\\mingw-w64\\include\\mingw-w64\\mpi.f90 exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\\mingw-w64\\include\\mingw-w64\\mpi.h exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\\mingw-w64\\lib\\mingw-w64\\msmpi.lib exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\\mingw-w64\\lib\\mingw-w64\\mpifort.lib exit 1  # [win]
    - if not %MSMPI_BIN% == %LIBRARY_PREFIX%\\mingw-w64\\bin exit 1  # [win]
    - if not %MSMPI_INC% == %LIBRARY_PREFIX%\\mingw-w64\\include exit 1  # [win]
    - if not %MSMPI_LIB64% == %LIBRARY_PREFIX%\\mingw-w64\\lib exit 1  # [win]

    # check if binaries work ok
    - where mpiexec.exe
    - where smpd.exe
    
    - mpiexec.exe /help2
    - mpiexec.exe /help3

    # This works! Just comment out to save time...
    ## test compiling + linking + execution
    #- git clone https://github.com/mpi4py/mpi4py.git
    #- cd mpi4py
    #- pip install --no-build-isolation --no-deps -v .
    #- cd ..
    #- python -c "from mpi4py import MPI; print(MPI.Get_library_version())"
    #- mpiexec -n 2 python -m mpi4py.bench helloworld
    #- mpiexec -n 2 python -m mpi4py.bench ringtest

    # check if MSMPI_VER is correctly patched
    - cl.exe -I%LIBRARY_PREFIX%\\mingw-w64\\include tests\\get_mpi_ver.c /Fe"%cd%\get_mpi_ver.exe"
    - for /f "tokens=* usebackq" %%f in (`get_mpi_ver`) do (set "mpi_ver=%%f")
    # TODO(leofang): we could compute this, yes, but don't bother as MS-MPI is not evolving...
    - if not %mpi_ver% == 2561 exit 1  # [win]  # for MS-MPI v10.1.x

    # check compiling & running simple C code
    # TODO(leofang): add C++ & Fortran tests?
    - cl.exe -I%LIBRARY_PREFIX%\\mingw-w64\\include tests\\helloworld.c /Fe"%cd%\helloworld.exe" /link /LIBPATH:"%LIBRARY_PREFIX%\\mingw-w64\\lib" msmpi.lib
    - mpiexec.exe -n 4 helloworld.exe

about:
  home: https://docs.microsoft.com/en-us/message-passing-interface/microsoft-mpi
  license: MIT
  license_file: LICENSE.txt
  summary: Microsoft message-passing-interface (MS-MPI)
  description: |
    Microsoft MPI (MS-MPI) is a Microsoft implementation of the Message Passing
    Interface standard for developing and running parallel applications on the
    Windows platform.
  doc_url: https://docs.microsoft.com/en-us/message-passing-interface/microsoft-mpi
  dev_url: https://github.com/microsoft/Microsoft-MPI

extra:
  recipe-maintainers:
    - RyanMcCarthy-NOAA
    - isuruf
