{% set name = "msmpi" %}
{% set version = "10.1.2" %}
{% set base_url = "http://download.microsoft.com/download/a/5/2/a5207ca5-1203-491a-8fb8-906fd68ae623/" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # See https://github.com/mpi4py/mpi4py/blob/master/.azure/install-msmpi.ps1

  # This is the MS-MPI SDK
  - url: {{ base_url }}msmpisdk.msi
    sha256: d8c07fc079d35d373e14a6894288366b74147539096d43852cb0bbae32b33e44

  # This is the MS-MPI Runtime
  - url: {{ base_url }}msmpisetup.exe
    sha256: c305ce3f05d142d519f8dd800d83a4b894fc31bcad30512cefb557feaccbe8b4

build:
  number: 0
  skip: true  # [not win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ compiler('m2w64_fortran') }}
  host:
    - 7zip
  run:
    - mpi 1.0 msmpi

test:
  commands:
    - if not exist %LIBRARY_BIN%\\mpiexec.exe exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\msmpi.dll exit 1  # [win]
    - if not exist %LIBRARY_INC%\\mpi.f90 exit 1  # [win]
    - if not exist %LIBRARY_INC%\\mpi.h exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\msmpi.lib exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\mpifort.lib exit 1  # [win]
    - if not %MSMPI_BIN% == %LIBRARY_BIN% exit 1  # [win]
    - if not %MSMPI_INC% == %LIBRARY_INC% exit 1  # [win]
    - if not %MSMPI_LIB64% == %LIBRARY_LIB% exit 1  # [win]

about:
  home: https://docs.microsoft.com/en-us/message-passing-interface/microsoft-mpi
  license: MIT
  license_file:
    - License\MicrosoftMPI-SDK-EULA.rtf
    - License\MicrosoftMPI_Redistributable_EULA.rtf
    - License\MPI-SDK-TPN.txt
    - License\MPI_Redistributables_TPN.txt
  summary: Microsoft message-passing-interface (MS-MPI)
  description: |
    Microsoft MPI (MS-MPI) is a Microsoft implementation of the Message Passing
    Interface standard for developing and running parallel applications on the
    Windows platform.
  doc_url: https://docs.microsoft.com/en-us/message-passing-interface/microsoft-mpi
  dev_url: https://github.com/microsoft/Microsoft-MPI

extra:
  recipe-maintainers:
    - RyanMcCarthy-NOAA
    - leofang
